title: Nackt in Ravensburg
author: Robert Da Silva
email: webmaster@robdasilva.com
description: Die Bachelorausstellung des Mediendesign-Studiengangs der DHBW Ravensburg 2014

permalink: /projekte/:title
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  style: compressed

timezone: UTC
